twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['bootstrap_4_layout.html.twig']
    globals:
        locales: [en, fr, de, es]

when@test:
    twig:
        strict_variables: true
