controllers:
    resource: ../src/Controller/
    type: attribute

frontend_index:
    path: /
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
    defaults:
        template: frontend/index.html.twig
